#----------------------------------------------------------------------------#
# BITS WLIP : Data Science
# Data Structures and Algorithms Design (S1-22_DSECSZG519)
# DSAD Group 05
# 	- AMIT KUMAR (2022cs04025)
# 	- NARESH KUMAR K S
# 	- RAJASEKHARUNI KRISHNA ARUN
#----------------------------------------------------------------------------#
# File Name: Makefile
# Input: None
# Output: executable 
#----------------------------------------------------------------------------#

all : queue_array queue_ll

clean :
	rm queue_array
	rm queue_ll
	rm sort
	rm BST

queue_array:
	gcc -Wall -pg main_qa.c queue_array_imp.c -o queue_array

queue_ll:
	gcc -Wall -pg main_qll.c queue_ll_imp.c -o queue_ll

sort:
	gcc -Wall -pg sort.c -o sort

BST:
	gcc -Wall -pg BST.c -o BST
