#----------------------------------------------------------------------------#
# BITS WLIP : Data Science
# Data Structures and Algorithms Design (S1-22_DSECSZG519)
# DSAD Group 05
# 	- AMIT KUMAR (2022cs04025)
# 	- NARESH KUMAR K S
# 	- RAJASEKHARUNI KRISHNA ARUN
#----------------------------------------------------------------------------#
# File Name: Makefile
# Input: None
# Output: executable 
#----------------------------------------------------------------------------#

all : assignment

clean :
	rm assignment

assignment :
	gcc main.c queue_array_imp.c queue_ll_imp.c bst.c -o assignment
	./assignment
